// <auto-generated />
using GraphQLProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20230914130309_SeedMenusTable")]
    partial class SeedMenusTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLProject.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tasty Vada Pav",
                            Name = "Vada Pav",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tasty Samosa",
                            Name = "Samosa",
                            Price = 25.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tasty Sada Dosa",
                            Name = "Sada Dosa",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tasty Masala Dosa",
                            Name = "Masala Dosa",
                            Price = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
